# Generated by Django 3.1.8 on 2021-09-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percent',
        ),
    ]
